# Generated by Django 5.1.7 on 2025-04-14 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_managers_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='address2',
        ),
        migrations.CreateModel(
            name='UserSecondaryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
