# Generated by Django 5.1.7 on 2025-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_created_at_product_stock_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
