# Generated by Django 5.1.7 on 2025-04-18 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tryon_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_images', to='store.product')),
            ],
        ),
    ]
