# Generated by Django 5.1.7 on 2025-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_tryonimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonimage',
            name='tag',
            field=models.CharField(blank=True, help_text='e.g. front view, side view', max_length=100),
        ),
    ]
