# Generated by Django 5.1.7 on 2025-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdetails_created_at_orderdetails_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='country',
            field=models.CharField(default='000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='mobile',
            field=models.CharField(default='Unknown Country', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='pincode',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
