# Generated by Django 5.1.7 on 2025-04-14 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetails_address_orderdetails_city_and_more'),
        ('payments', '0002_paymentdetails_created_at_paymentdetails_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.paymentdetails'),
        ),
    ]
